# Generated by Django 4.2.6 on 2023-10-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ManyToManyField(to='base.photo', verbose_name='Фотографии пользователя'),
        ),
    ]
