# Generated by Django 4.2.6 on 2023-10-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
