# Generated by Django 4.2.6 on 2023-10-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_photo_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='photo',
            name='resize',
            field=models.ImageField(blank=True, null=True, upload_to='resize/'),
        ),
    ]
