# Generated by Django 4.2.6 on 2023-10-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_photo_thumbnail_photo_resize'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('Научная', 'Научная'), ('Портрет', 'Портрет'), ('Бытовая', 'Бытовая'), ('Другое', 'Другое')], default='Другое', max_length=100, verbose_name='Тип фото'),
        ),
        migrations.AddField(
            model_name='photo',
            name='isopen',
            field=models.BooleanField(default=1),
        ),
    ]
