# Generated by Django 4.2.6 on 2023-10-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_photo_category_photo_isopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='avtor',
            field=models.CharField(default='none', max_length=60),
        ),
    ]
