# Generated by Django 4.2.6 on 2023-10-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_photo_avtor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='avtor',
        ),
    ]
