# Generated by Django 4.0.2 on 2023-10-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_photo_avtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ManyToManyField(to='base.Photo', verbose_name='Фотографии пользователя'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'password')},
        ),
    ]
