# Generated by Django 4.2.6 on 2023-10-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_album_face_alter_album_photoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='face',
        ),
        migrations.AddField(
            model_name='album',
            name='resize',
            field=models.ImageField(blank=True, null=True, upload_to='resize/'),
        ),
    ]
