# Generated by Django 4.2.6 on 2023-10-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_album_face_album_resize'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ManyToManyField(blank=True, null=True, to='base.photo', verbose_name='Фотографии пользователя'),
        ),
    ]
